tests: Fix test failures not to end in timeout
Previously a test failure also killed the test driver
script.  Which lead to meson not reporting the failure,
but reporting a timeout instead.

Signed-off-by: Frank Lichtenheld <frank@lichtenheld.com>

diff --git a/tests/scripts/run-simple-server-test b/tests/scripts/run-simple-server-test
--- a/tests/scripts/run-simple-server-test
+++ b/tests/scripts/run-simple-server-test
@@ -44,8 +44,11 @@ run_test()
     echo "-----------------------------------------------------------"
     echo "###  Running test: $@"
     echo
+    # Do not fail the test driver when the test fails
+    set +e
     eval $@
     ec=$?
+    set -e
     echo
     echo ".."
     if [ ${ec} -ne 0 ]; then
